FROM ubuntu:latest
#Setup Environment
ENV BOTFileName bot.py
ENV Pip_Depenendcies "pythonping iperf3" 
ENV Apt_Dependencies "iperf3"
VOLUME ["/mnt/bot"]
WORKDIR /mnt/bot

#Install Deps
RUN apt-get update && apt-get -y install sudo
RUN sudo apt install -y python3 python3-pip curl
RUN sudo apt install -y ${Apt_Dependencies}
RUN sudo apt update
RUN pip3 install discord.py==1.5.0 requests pytz simplejson docker
RUN pip3 install ${Pip_Depenendcies}

RUN echo "Installed Depenendcies"

#Run Bot
CMD python3 ${BOTFileName}
